dist: bionic

language: python

services:
  - docker

python:
  - 3.7
  - 3.8

stages:
  - test
  - lint

cache:
  pip: true
  cargo: true

before_cache:
  - rm -rfv target/debug/incremental/{tantivy,build_script_build,common}-*
  - rm -rfv target/debug/.fingerprint/tantivy-*
  - rm -rfv target/debug/build/tantivy-*
  - rm -rfv target/debug/deps/libtantivy-*
  - rm -rfv target/debug/deps/tantivy-*
  - rm -rfv target/debug/{tantivy,libtantivy}.d
  - cargo clean -p tantivy-py

env:
  global:
    - PIPENV_VERBOSITY=-1
    - TRAVIS_RUST_VERSION=nightly
    - RUST_BACKTRACE=1

install:
  - pip install --upgrade pip
  - pip install -U pipenv
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
  - source "$HOME"/.cargo/env
  - pipenv install --dev .

before_script:
  - rustc --version
  - python --version

matrix:
  include:
    - python: 3.7
      name: 'rust linters'
      install: rustup component add clippy rustfmt
      script:
        - cargo clippy
        - cargo fmt -- --check
      stage: lint

script:
  - pipenv run py.test -rws -v tests/
