[package]
name = "tantivy-py"
version = "0.10.1"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "MIT"

[lib]
name = "tantivy"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4"
tantivy = "0.11"
itertools = "0.8"
futures = "0.3"

[dependencies.pyo3]
version = "0.8"
features = ["extension-module"]
